apiVersion: v1 # padrão
kind: Pod # recurso 
metadata: 
  name: nginx
  labels:
    app: nginx
    release: stable
spec: # configurações dos containers
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  restartPolicy: OnFailure
  liveinessProbe:
    httpGet:
      path: /index.html
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /index.html
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5