apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: voting-app
    tier: database
spec:
  selector:
    name: postgres-pod
    app: voting-app
    tier: database
  ports:
  - port: 5432
    targetPort: 5432
