apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-app
      tier: backend
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app
        tier: backend
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1

